version: '3.9'

services:

  postgres:
    image: postgres:13.0-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      timeout: 3s
      retries: 3

  api:
    image: ${DOCKERHUB_USERNAME}/todolist_diploma6:latest
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    image: sermalenk/skypro-front:lesson-35
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf



volumes:
  pg_data:
